
services:
  mysql:
    container_name: mysql-crm
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 2334
      MYSQL_DATABASE: crm_dev
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 2334
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - spring-demo
    restart: unless-stopped

volumes:
  mysql:
    driver: local

networks:
  spring-demo:
    driver: bridge
