services:
  postgres:
    container_name: postgres-sql-crm
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2334
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: crm_dev
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped




volumes:
  postgres:
    driver: local

networks:
  spring-demo:
    driver: bridge