spring:
  application:
    name: crm-dev
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
server:
  servlet:
    context-path: /api/v1/


logging:
  level:
    root: info

  file:
    name: logs/crm-dev.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"